apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: anonymous
  deployment:
    accessible_namespaces: ["**"]
  external_services:
    tracing:
      enabled: true
      use_grpc: true
      # Updated to point to central-observability
      in_cluster_url: "http://tempo-tempo-query-frontend.central-observability.svc.cluster.local:16685"
      url: "" 
    grafana:
      enabled: true
      in_cluster_url: "http://grafana.central-observability.svc.cluster.local:3000"
      url: "grafana-central-observability.apps.ocp4.masales.cloud"
